theme: jekyll-theme-minimal
font-icon: /assets/css/font-awesome-4.7.0/css/font-awesome.min.css

# 你的求职方向，比如前端开发工程师等
title: 歌手、演员

# 对你自己的简洁描述
description: 完美声线；清脆如天籁的嗓音；创作、打鼓、跳舞、弹吉他、弹琴、小号样样行

# 你的美照地址
logo: ![](https://i.loli.net/2021/01/04/L8z1WcOhpuVCilG.jpg)

# 你的名字
name: 贾斯汀·比伯（Justin Bieber）

# 你的联系方式
phone: @justinbieber

# 你的邮箱
email: ustinnbieber@windowslive.com

# 你目前的住址
address: Atlanta Botanical （亚特兰大）

# 你毕业院校
school: 加拿大圣迈克尔天主教高中

# 你的专业
profession: 歌手

# 你的学位
degree: 高中毕业

# 你获得过的证书或奖励
credential: 第58届格莱美最佳舞曲录制奖
